build:
  image: cboettig/2016
  commands:
    - R -e "devtools::install_github('cboettig/appl')"
    - R -e "status <- devtools::check(); testthat::expect_length(status$errors, 0); testthat::expect_length(status$warnings, 0)"

