build:
  image: cboettig/2016
  commands:
    #    - R -e "devtools::install_github('cboettig/appl')"
    - R -e "status <- devtools::check(); err <- status$errors; msg <- status$warnings; testthat::expect_length(err, 0); testthat::expect_length(msg, 0)"
    - R -e "sessionInfo()"
