---
output:
  html_document: 
    keep_md: yes
    variant: markdown_github
---  



```{r}
library("MDPtoolbox")
library("appl")
library("ggplot2")
library("dplyr")
knitr::opts_chunk$set(cache = TRUE)
```

```{r}
source("pomdp_learning.R")
```


## Problem definition

```{r}
states <- 0:40
actions <- states
obs <- states

sigma_g <- sqrt(log(1 + 0.1 / 6)) # Scale the log-standard-deviation to result in similar variance to a uniform distribution of width 0.5
sigma_m <- sigma_g

reward_fn <- function(x,h) pmin(x,h)
discount <- 0.95


K1 <- function(x, h, r = 1, K = 20){
  s <- pmax(x - h, 0)
  s * exp(r * (1 - s / K) )
}


K2 <- function(x, h, r = 1, K = 25){
  s <- pmax(x - h, 0)
  s * exp(r * (1 - s / K) )
}



K3 <- function(x, h, r = 1, K = 30){
  s <- pmax(x - h, 0)
  s * exp(r * (1 - s / K) )
}



r1 <- function(x, h, r = 0.2, K = 30){
  s <- pmax(x - h, 0)
  s * exp(r * (1 - s / K) )
}

r2 <- function(x, h, r = 1, K = 30){
  s <- pmax(x - h, 0)
  s * exp(r * (1 - s / K) )
}


r3 <- function(x, h, r = 1.8, K = 30){
  s <- pmax(x - h, 0)
  s * exp(r * (1 - s / K) )
}

Ks <- list(K1, K2, K3)
rs <- list(r1, r2, r3)


```


```{r}

K_models <- lapply(Ks, function(f) fisheries_matrices(states, actions, obs, reward_fn, f, sigma_g, sigma_m))
r_models <- lapply(rs, function(f) fisheries_matrices(states, actions, obs, reward_fn, f, sigma_g, sigma_m))

```


## Planning solution

Compute Q matrices using pomdpsol for each model (intensive)

```{r}
K_Qs <- init_models(K_models, discount, verbose, precision = 1)
```

```{r}
r_Qs <- init_models(K_models, discount, verbose, precision = 1)
```

Use Qs to compute policy given model priors, for comparison:

```{r}
compare_policies <- function(Qs){
  low <- compute_policy(Qs, c(1, 0, 0))
  unif <- compute_policy(Qs, c(1/3, 1/3, 1/3))
  high <- compute_policy(Qs, c(0, 1/3, 1))
  
  dplyr::bind_rows(low, unif, high, .id = "prior")
}

```


```{r}
df <- compare_policies(K_Qs)

ggplot(df, aes(states[state], states[state] - actions[policy], col = prior, pch = prior)) + 
  geom_point(alpha = 0.5, size = 3) + 
  geom_line()
```



```{r}
df <- compare_policies(r_Qs)

ggplot(df, aes(states[state], states[state] - actions[policy], col = prior, pch = prior)) + 
  geom_point(alpha = 0.5, size = 3) + 
  geom_line() 
```

